package org.example.request_and_response;

public enum CommandType {
    AVERAGE_OF_DISTANCE, CLEAR, COUNT_BY_DISTANCE, EXECUTE_SCRIPT, EXIT, FILTER_LESS_THAN_DISTANCE, HELP, INFO,
    INSERT, REMOVE_GREATER, REMOVE_GREATER_KEY, REMOVE_KEY, REPLACE_IF_LOWER, SHOW, UPDATE, SAVE_SERVER
}
